# Generated by Django 4.1.3 on 2023-10-24 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_usersubscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSubscription',
        ),
    ]
